import { FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './style.css'

type Severity = 'reported' | 'confirmed' | 'critical'
type ImpactSeverity = 'low' | 'medium' | 'high' | 'critical'
type Incident = { id: string; category: string; description: string; location: Location; imageUrl?: string | null; impactSeverity: ImpactSeverity; analysisConfidence: number; reportCount: number; firstReported: number; lastReported: number; resolutionStatus: 'open' | 'proposed' | 'resolved'; resolutionCount: number }
type Prediction = { location: string; floodDays: number; rainDays: number }
type Location = { label: string; lat: number; lng: number }
type AnalysisResult = { candidateCount: number; matched: boolean; matchId: string | null; matchDescription: string | null; matchConfidence: number; previousCount: number; previousSeverity: Severity; currentSeverity: Severity; location: Location; category: string; impactSeverity: ImpactSeverity }
type AnalysisState = { stage: number; report: string; accuracy: number; incident?: Incident; result?: AnalysisResult }
type LeafletMap = { setView: (position: [number, number], zoom?: number) => LeafletMap; on: (event: string, handler: (event: { latlng: { lat: number; lng: number } }) => void) => void; remove: () => void }

declare global { interface Window { L?: any } }

const AREA_KEY = 'civicpulse-area-v1'
const kochi: Location = { label: 'Kochi Metro corridor', lat: 9.9816, lng: 76.2999 }

const severity = (count: number): Severity => count >= 6 ? 'critical' : count >= 3 ? 'confirmed' : 'reported'
const age = (time: number) => { const days = Math.floor((Date.now() - time) / 86_400_000); return days ? `open ${days} day${days === 1 ? '' : 's'}` : 'reported today' }
const readArea = () => { try { return JSON.parse(localStorage.getItem(AREA_KEY) ?? 'null') as Location | null ?? kochi } catch { localStorage.removeItem(AREA_KEY); return kochi } }
const voterId = () => localStorage.getItem('civicpulse-voter-id') ?? (() => { const id = crypto.randomUUID(); localStorage.setItem('civicpulse-voter-id', id); return id })()
const freshGps = () => new Promise<{ location: Location; accuracy: number }>((resolve, reject) => navigator.geolocation.getCurrentPosition(position => resolve({ location: { label: 'Your current location', lat: position.coords.latitude, lng: position.coords.longitude }, accuracy: position.coords.accuracy }), reject, { enableHighAccuracy: true, timeout: 20_000, maximumAge: 0 }))

function Map({ incidents, area, onSelect }: { incidents: Incident[]; area: Location; onSelect: (id: string) => void }) {
  const map = useRef<LeafletMap | null>(null)
  const layer = useRef<{ clearLayers: () => void; addLayer: (marker: unknown) => void } | null>(null)
  useEffect(() => { if (!window.L || map.current) return; const leaf = window.L.map('map', { zoomControl: false }).setView([area.lat, area.lng], 12); map.current = leaf; window.L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: '© OpenStreetMap contributors' }).addTo(leaf); layer.current = window.L.layerGroup().addTo(leaf) }, [])
  useEffect(() => { if (!window.L || !map.current || !layer.current) return; map.current.setView([area.lat, area.lng]); layer.current.clearLayers(); incidents.forEach(incident => { const sameSpot = incidents.filter(item => item.location.lat === incident.location.lat && item.location.lng === incident.location.lng); const index = sameSpot.findIndex(item => item.id === incident.id); const angle = sameSpot.length > 1 ? (Math.PI * 2 * index) / sameSpot.length : 0; const offset = sameSpot.length > 1 ? `transform:translate(${Math.cos(angle) * 21}px,${Math.sin(angle) * 21}px)` : ''; const marker = window.L!.marker([incident.location.lat, incident.location.lng], { icon: window.L!.divIcon({ className: '', html: `<div class="pin-wrap" style="${offset}"><div class="marker impact-${incident.impactSeverity} ${severity(incident.reportCount)}"></div></div>`, iconSize: [70, 70], iconAnchor: [35, 35] }) }).addTo(layer.current!); marker.bindPopup(`<b>${incident.category}</b><br>${incident.description}`).on('click', () => onSelect(incident.id)) }) }, [incidents, area, onSelect])
  return <div className="map-shell"><div id="map">{!window.L && <p className="map-error">Map tiles are unavailable. Your reports still work.</p>}</div><div className="map-hud"><span className="live-dot" /> {incidents.length} live reports</div><div className="legend"><span><i className="impact-low" />Low</span><span><i className="impact-medium" />Medium</span><span><i className="impact-high" />High</span><span><i className="impact-critical" />Critical impact</span></div></div>
}

function AnalysisPanel({ analysis }: { analysis: AnalysisState }) {
  const { stage, report, accuracy, result, incident } = analysis
  return <section className="analysis-panel" aria-live="polite"><p className="analysis-title"><span className="live-dot" /> AI incident analysis</p><div className={stage >= 1 ? 'analysis-step active' : 'analysis-step'}><b>✓ Report received</b><span>“{report}”</span></div>{stage >= 2 && <div className="analysis-step active"><b>Location analysis</b><span>{result?.location.label ?? 'Extracting GPS location…'} · GPS ±{Math.round(accuracy)} m</span></div>}{stage >= 3 && <div className="analysis-step active"><b>Structured extraction</b><span>Category: {result?.category ?? 'Classifying'} · Impact: {result?.impactSeverity ?? 'Assessing'}</span></div>}{stage >= 4 && <div className="analysis-step active"><b>Duplicate detection</b><span>Checked {result?.candidateCount ?? 0} nearby active incidents</span>{result?.matched && <><strong>Potential match · Incident {result.matchId?.slice(0, 8)}</strong><div className="confidence"><i style={{ width: `${result.matchConfidence}%` }} />{result.matchConfidence}% confidence</div></>}</div>}{stage >= 5 && result && <div className="analysis-step active"><b>Decision</b><strong>{result.matched ? `Merge into incident ${result.matchId?.slice(0, 8)}` : 'Create new incident'}</strong><span>{result.matched ? 'Same nearby location and semantic match' : 'No nearby incident passed the match threshold'}</span></div>}{stage >= 6 && result && <div className="analysis-step active"><b>Community intelligence</b><span>Reports {result.previousCount} → {incident?.reportCount ?? result.previousCount + 1}</span><span>Community status: {result.previousSeverity} → {result.currentSeverity}</span></div>}{stage >= 7 && result && <div className="analysis-summary"><b>✓ Incident updated</b><span>{result.matched ? 'Merged into shared community knowledge' : 'New incident added to the live map'}</span><span>Impact: {result.impactSeverity} · Pulse refreshed</span></div>}</section>
}

function letterFor(incident: Incident) { const authority = incident.category === 'METRO DELAY' ? 'Kochi Metro Rail Limited' : incident.category === 'POWER CUT' ? 'Kerala State Electricity Board' : 'Kochi Municipal Corporation'; return `To: ${authority}\n\nSubject: Request to address ${incident.category.toLowerCase()} at ${incident.location.label}\n\nDear Sir/Madam,\n\nI am writing to report ${incident.description} This issue has been ${age(incident.firstReported)} and has received ${incident.reportCount} community reports. I request that it be inspected and addressed at the earliest.\n\nSincerely,\nA concerned commuter` }

function App() {
  const [incidents, setIncidents] = useState<Incident[]>([])
  const [area, setArea] = useState(readArea)
  const [locationReady, setLocationReady] = useState(false)
  const [locationError, setLocationError] = useState<string | null>(null)
  const [locationAccuracy, setLocationAccuracy] = useState<number | null>(null)
  const [text, setText] = useState('')
  const [image, setImage] = useState<File | null>(null)
  const [apiError, setApiError] = useState<string | null>(null)
  const [prediction, setPrediction] = useState<Prediction | null>(null)
  const [analysis, setAnalysis] = useState<AnalysisState | null>(null)
  const [selected, setSelected] = useState<Incident | null>(null)
  const [letter, setLetter] = useState<Incident | null>(null)
  const [resolutionOpen, setResolutionOpen] = useState(false)
  const [resolutionNote, setResolutionNote] = useState('')
  const [resolutionImage, setResolutionImage] = useState<File | null>(null)
  const [resolutionError, setResolutionError] = useState<string | null>(null)
  const open = useMemo(() => [...incidents].sort((a, b) => b.reportCount - a.reportCount), [incidents])
  const load = async () => { try { const [response, predictionResponse] = await Promise.all([fetch('/api/incidents'), fetch('/api/predictions')]); if (!response.ok || !response.headers.get('content-type')?.includes('application/json')) return setApiError('Live data is unavailable. Start the CivicPulse API to load reports.'); setIncidents(await response.json() as Incident[]); if (predictionResponse.ok && predictionResponse.headers.get('content-type')?.includes('application/json')) setPrediction((await predictionResponse.json() as Prediction[])[0] ?? null); setApiError(null) } catch { setApiError('Live data is unavailable. Start the CivicPulse API to load reports.') } }
  useEffect(() => { if (analysis) return; void load(); const timer = setInterval(() => void load(), 5_000); return () => clearInterval(timer) }, [analysis])
  useEffect(() => { if (!navigator.geolocation) return setLocationError('This browser cannot provide your location.'); const watch = navigator.geolocation.watchPosition(position => { const next = { label: 'Your current location', lat: position.coords.latitude, lng: position.coords.longitude }; const accurate = position.coords.accuracy <= 150; localStorage.setItem(AREA_KEY, JSON.stringify(next)); setArea(next); setLocationAccuracy(position.coords.accuracy); setLocationReady(accurate); setLocationError(accurate ? null : `Location is only accurate to ±${Math.round(position.coords.accuracy)} m. Use a GPS-enabled device or wait for a better signal.`) }, () => { setLocationReady(false); setLocationError('Location permission is required to submit a report.') }, { enableHighAccuracy: true, timeout: 20_000, maximumAge: 0 }); return () => navigator.geolocation.clearWatch(watch) }, [])
  const requestLocation = async () => { try { const { location, accuracy } = await freshGps(); const accurate = accuracy <= 150; localStorage.setItem(AREA_KEY, JSON.stringify(location)); setArea(location); setLocationAccuracy(accuracy); setLocationReady(accurate); setLocationError(accurate ? null : `Location is only accurate to ±${Math.round(accuracy)} m. Move outdoors or enable precise location.`) } catch { setLocationReady(false); setLocationError('Location access is blocked. Allow Location for this site in your browser settings, then select Enable location.') } }
  const submit = async (event: FormEvent) => { event.preventDefault(); const description = text.trim(); if (!description || !locationReady) return; try { const { location, accuracy } = await freshGps(); if (accuracy > 150) throw new Error(`GPS is only accurate to ±${Math.round(accuracy)} m.`); localStorage.setItem(AREA_KEY, JSON.stringify(location)); setArea(location); setLocationAccuracy(accuracy); setAnalysis({ stage: 1, report: description, accuracy }); const body = new FormData(); body.append('description', description); body.append('location', JSON.stringify(location)); if (image) body.append('image', image); const response = await fetch('/api/incidents/report', { method: 'POST', body }); if (!response.ok) throw new Error('Incident analysis could not be completed.'); const payload = await response.json() as { incident: Incident; analysis: AnalysisResult }; setText(''); setImage(null); setAnalysis(current => current ? { ...current, incident: payload.incident, result: payload.analysis } : null) } catch (error) { setAnalysis(null); setLocationReady(false); setLocationError(error instanceof Error ? `${error.message} Move outdoors or enable precise location, then retry.` : 'A fresh GPS location is required.') } }
  useEffect(() => { if (!analysis?.result || !analysis.incident) return; const stages = [400, 900, 1_600, 2_400, 3_000, 3_600, 4_100].map((delay, index) => setTimeout(() => { const stage = index + 2; setAnalysis(current => current ? { ...current, stage } : null); if (stage === 7) setIncidents(current => current.some(item => item.id === analysis.incident!.id) ? current.map(item => item.id === analysis.incident!.id ? analysis.incident! : item) : [analysis.incident!, ...current]); if (stage === 8) { void load(); setTimeout(() => setAnalysis(null), 350) } }, delay)); return () => stages.forEach(clearTimeout) }, [analysis?.result])
  const upvote = async (incident: Incident) => { const response = await fetch(`/api/incidents/${incident.id}/upvotes`, { method: 'POST', headers: { 'x-voter-id': voterId() } }); if (response.ok) { const result = await response.json() as { incident: Incident }; setIncidents(current => current.map(item => item.id === incident.id ? result.incident : item)); setSelected(result.incident) } }
  const verifyResolution = async (incident: Incident) => { try { setResolutionError(null); const { location, accuracy } = await freshGps(); if (accuracy > 150) throw new Error(`GPS is only accurate to ±${Math.round(accuracy)} m.`); const body = new FormData(); body.append('location', JSON.stringify(location)); body.append('note', resolutionNote); if (resolutionImage) body.append('image', resolutionImage); const response = await fetch(`/api/incidents/${incident.id}/resolutions`, { method: 'POST', headers: { 'x-voter-id': voterId() }, body }); const payload = response.headers.get('content-type')?.includes('application/json') ? await response.json() as { incident?: Incident; error?: string } : {}; if (!response.ok || !payload.incident) throw new Error(payload.error ?? (response.status === 404 ? 'Resolution service is unavailable. Restart npm run dev:api, then retry.' : 'Resolution verification could not be submitted.')); setResolutionNote(''); setResolutionImage(null); setResolutionOpen(false); if (payload.incident.resolutionStatus === 'resolved') { setIncidents(current => current.filter(item => item.id !== incident.id)); setSelected(null); void load() } else { setIncidents(current => current.map(item => item.id === incident.id ? payload.incident! : item)); setSelected(payload.incident) } } catch (error) { setResolutionError(error instanceof Error ? error.message : 'A fresh GPS location is required to verify this resolution.') } }
  const critical = open.filter(incident => severity(incident.reportCount) === 'critical').length
  const confirmations = open.reduce((total, incident) => total + incident.reportCount, 0)
  return <>
    <header><div><h1>Civic<span>Pulse</span></h1><p>Community-powered civic intelligence</p></div><span className="tag"><i className="live-dot" /> Kochi civic board</span></header>
    <main className="dashboard">
      <aside className="sidebar">
        <p className="notice"><b>How it works</b><br />Report once, confirm together. Critical issues become impossible to ignore.</p>
        {apiError && <p className="api-error">{apiError}</p>}
        <p className="pulse">{critical ? `${critical} critical issue${critical > 1 ? 's' : ''} need attention; ${open.length - critical} other live reports nearby.` : `${open.length} live community reports across Kochi.`}</p>
        <p className="prediction"><b>{prediction ? 'Community flood warning' : 'Flood prediction'}</b><br />{prediction ? `Rain-related reports are active — ${prediction.location} flooded on ${prediction.floodDays} of ${prediction.rainDays} recorded rain days.` : 'Warnings will appear after citizens report repeated flooding during rain at the same location.'}</p>
        <section className="stats"><div><b>{open.length}</b><span>Open now</span></div><div><b>{critical}</b><span>Critical</span></div><div><b>{confirmations}</b><span>Reports</span></div></section>
        <section className="composer"><div className="section-title"><h2>Report an issue</h2><span>{locationReady ? 'GPS location ready' : 'Finding your location'}</span></div><form onSubmit={submit}><input value={text} onChange={event => setText(event.target.value)} maxLength={240} placeholder="What's happening? e.g. Metro stuck near Kaloor" aria-label="Describe a civic issue" /><p className="pin-status">📍 {locationError ?? (locationReady ? `GPS accuracy ±${Math.round(locationAccuracy ?? 0)} m · ${area.lat.toFixed(4)}, ${area.lng.toFixed(4)}` : 'Waiting for location permission…')}</p>{!locationReady && <button type="button" className="secondary location-button" onClick={() => void requestLocation()}>Enable location</button>}<label className="upload">⌁ {image ? image.name : 'Add a photo (optional)'}<input type="file" accept="image/*" onChange={event => setImage(event.target.files?.[0] ?? null)} /></label><button disabled={!locationReady}>Submit report</button></form></section>
        <div className="section-title"><h2>Open incidents</h2><span className="meta">Live updates</span></div>
        <section className="feed">{open.length ? open.map(incident => <article className="card incident" key={incident.id} onClick={() => setSelected(incident)}><span className={`dot impact-${incident.impactSeverity}`} /><div><h3>{incident.category} · {incident.location.label}</h3><p>{incident.description}</p>{incident.imageUrl && <img className="incident-image" src={incident.imageUrl} alt="Report evidence" />}<p className="meta">{age(incident.firstReported)} · <span className={`impact impact-${incident.impactSeverity}`}>{incident.impactSeverity} impact</span> · {severity(incident.reportCount)}</p></div><span className="count">{'│'.repeat(Math.min(incident.reportCount, 8))} {incident.reportCount}</span></article>) : <div className="empty"><b>No reports yet</b><span>Be the first commuter to report an issue nearby.</span></div>}</section>
      </aside>
      <section className="map-panel"><Map incidents={open} area={area} onSelect={id => setSelected(incidents.find(incident => incident.id === id) ?? null)} />{analysis && <AnalysisPanel analysis={analysis} />}</section>
    </main>
    {selected && <div className="backdrop"><section className="modal"><p className="tag">{severity(selected.reportCount)} · {age(selected.firstReported)}</p><h2>{selected.category}</h2><p><span className={`impact impact-${selected.impactSeverity}`}>{selected.impactSeverity} impact</span></p><p>{selected.description}</p>{selected.imageUrl && <img className="modal-image" src={selected.imageUrl} alt="Report evidence" />}<p className="meta">{selected.location.label} · {selected.reportCount} community confirmations</p>{severity(selected.reportCount) === 'critical' && <section className="critical-reasons"><h3>Why this is critical</h3><span>✓ {selected.reportCount} community reports (critical threshold: 6)</span><span>✓ {age(selected.firstReported)}</span><span>✓ {selected.impactSeverity} impact</span>{selected.analysisConfidence > 0 && <span>✓ AI match confidence: {selected.analysisConfidence}%</span>}</section>}<section className="resolution"><b>{selected.resolutionStatus === 'proposed' ? `Resolution proposed · ${selected.resolutionCount}/2 nearby confirmations` : 'Is this fixed?'}</b><span>Two different nearby residents must confirm a resolution before it leaves the live board.</span>{resolutionOpen && <div className="resolution-form"><input value={resolutionNote} onChange={event => setResolutionNote(event.target.value)} maxLength={240} placeholder="Resolution note (optional)" /><label className="upload">⌁ {resolutionImage ? resolutionImage.name : 'Add resolution photo (optional)'}<input type="file" accept="image/*" onChange={event => setResolutionImage(event.target.files?.[0] ?? null)} /></label>{resolutionError && <p className="resolution-error">{resolutionError}</p>}<button onClick={() => void verifyResolution(selected)}>Confirm resolution nearby</button></div>}</section><div className="actions"><button onClick={() => void upvote(selected)}>Confirm issue</button><button onClick={() => { setResolutionError(null); setResolutionOpen(open => !open) }}>{resolutionOpen ? 'Cancel' : selected.resolutionStatus === 'proposed' ? 'Verify resolution' : 'Mark resolved'}</button>{severity(selected.reportCount) === 'critical' && <button onClick={() => setLetter(selected)}>View draft letter</button>}<button className="secondary" onClick={() => { setResolutionError(null); setResolutionOpen(false); setSelected(null) }}>Close</button></div></section></div>}
    {letter && <div className="backdrop"><section className="modal"><h2>Draft complaint</h2><pre>{letterFor(letter)}</pre><div className="actions"><button className="secondary" onClick={() => setLetter(null)}>Close</button><button onClick={() => navigator.clipboard.writeText(letterFor(letter))}>Copy letter</button></div></section></div>}
  </>
}

createRoot(document.getElementById('root')!).render(<App />)
